/**
 * Triage for the threads the OLD inferred queue was built from.
 *
 * Membership used to be derived: a thread was in "For Your Review" whenever an
 * agent had spoken last and no person had answered. That is true of every
 * status note any agent has ever posted, so the queue filled with receipts —
 * 105 rows on the live workspace, 6 of them questions. Declaring replaces the
 * inference, and this module decides what to do with what the inference left
 * behind.
 *
 * Three dispositions, and only ONE of them is a script's to carry out:
 *
 *  - `question`  — the run contains a real question. **Emitted for an agent to
 *    read**, never actioned here. Turning one into a Review Item means writing
 *    a headline and a why, and a headline generated by clipping a comment is
 *    precisely the row shape this whole change exists to delete.
 *  - `receipt`   — the run opens with a closing verb ("Done", "Merged",
 *    "Fixed"). Self-evidently a note about finished work; safe to soft-resolve
 *    in a batch.
 *  - `skim`      — neither. The closing-verb test is a heuristic and this is
 *    the half it cannot speak for, so these are **listed, not resolved**.
 *
 * Soft only. The action is `resolve`, which is the mechanism that already
 * exists: a resolved thread leaves the queue, stays completely readable, and
 * any person replying reopens it. No comment and no thread is ever deleted —
 * the `.ydoc` is the durable record `activity-backfill.ts` rebuilds analysis
 * from, not a cache.
 *
 * Age is deliberately NOT a criterion. Measured on the live board before this
 * was written: the 30 newest rows were 0-for-30 on questions and the oldest
 * row on the board was not one either. Age would retire live threads and keep
 * dead ones.
 *
 * 2026-08-21: the queue route itself stopped emitting inference-only rows —
 * membership is now "a pending declaration or a direct ask", so receipts no
 * longer reach `fetchQueueRows` and there is nothing left for this script to
 * resolve. The queue is derived per request; the leftover rows retired
 * themselves the moment membership changed, with no thread touched. The
 * script is kept for its report (`question` rows still surface here) and the
 * pure classifier still serves tooling, but its resolve pass is expected to
 * be a no-op against any server running the new rule.
 */
import type { Comment, Thread } from '@claude-workspaces/core';
import { asksPerson } from './ask-detection.ts';
import { knownPeople, unansweredRun } from './review-queue.ts';

export type Disposition = 'question' | 'receipt' | 'skim';

export interface ThreadTriage {
  docId: string;
  threadId: string;
  disposition: Disposition;
  /** How many comments the person has not answered. */
  runLength: number;
  /** The first line of the run's opening comment, for the printed table. */
  excerpt: string;
  /** Who spoke last in the run. */
  lastBy: string;
  /** The run's oldest comment — how long this has been sitting. */
  since: number;
  /** Already carries a declaration, so the new queue holds it and nothing here
   *  applies. Kept in the report rather than filtered out, because a run that
   *  vanishes between two passes is indistinguishable from one this script
   *  quietly resolved. */
  declared: boolean;
}

/**
 * Verbs a comment opens with when it is reporting finished work.
 *
 * Matched at the START of the opening comment only. A "done" in the middle of
 * a sentence ("let me know when you're done") says the opposite, and matching
 * anywhere would classify that as a receipt and resolve it.
 */
const CLOSING_VERBS = [
  'done',
  'fixed',
  'merged',
  'shipped',
  'landed',
  'deployed',
  'pushed',
  'resolved',
  'agreed',
  'recorded',
  'noted',
  'updated',
  'added',
  'removed',
  'reverted',
  'confirmed',
  'implemented',
  'completed',
];

/** Leading markdown a comment routinely opens with, none of which changes what
 *  the first word is: emphasis runs, a bullet, a heading, a check mark. */
const LEADING_NOISE = /^[\s>*_`#\-+✓✅☑•]+/;

/**
 * Does this comment open by reporting finished work?
 *
 * Exported because it is the whole basis of the `receipt` class, and the class
 * is what a batch resolve acts on — so it needs to be assertable on its own,
 * against the phrasings that nearly fooled it.
 */
export function opensWithClosingVerb(text: string): boolean {
  const head = text.replace(LEADING_NOISE, '').toLowerCase();
  for (const verb of CLOSING_VERBS) {
    if (!head.startsWith(verb)) continue;
    // The next character has to end the word, or "doneness" and "Adding" match
    // the verb they merely start with. The markdown closers are in the class
    // for the same reason the opener noise is stripped: `**Fixed** the header`
    // is one of the commonest ways an agent opens a receipt, and without `*`
    // here it reads as an unknown word and lands in the skim pile.
    const next = head.charAt(verb.length);
    if (next === '' || /[\s,.;:!*_`—–-]/.test(next)) return true;
  }
  return false;
}

/**
 * Classify one thread.
 *
 * `people` is the set of names an address may name — the same set the live
 * queue's ask detector uses, so "is this a question" has one answer across the
 * product rather than a second opinion written for the migration.
 */
export function triageThread(
  docId: string,
  thread: Thread,
  people: Iterable<string>,
): ThreadTriage | null {
  const run = unansweredRun(thread);
  const first = run[0];
  const last = run[run.length - 1];
  if (!first || !last) return null;

  const declared = run.some((c) => c.review !== undefined);
  const disposition: Disposition = run.some((c) => asksPerson(c.text, people))
    ? 'question'
    : opensWithClosingVerb(first.text)
      ? 'receipt'
      : 'skim';

  return {
    docId,
    threadId: thread.id,
    disposition,
    runLength: run.length,
    excerpt: excerptOf(first),
    lastBy: authorName(last),
    since: first.ts,
    declared,
  };
}

function authorName(c: Comment): string {
  const a = c.author as unknown;
  if (typeof a === 'string') return a;
  const name = (a as { name?: unknown } | null)?.name;
  return typeof name === 'string' && name !== '' ? name : 'unknown';
}

function excerptOf(c: Comment): string {
  const one = c.text.replace(/\s+/g, ' ').trim();
  return one.length > 72 ? `${one.slice(0, 71)}…` : one;
}

export interface MigrationPlan {
  triaged: ThreadTriage[];
  counts: Record<Disposition, number>;
  /** Runs that already declare. Nothing here is actionable — they are the new
   *  queue — but the number belongs in the report so the two passes add up. */
  declared: number;
}

/**
 * Triage a whole set of threads, deriving the people roster from all of them.
 *
 * The roster comes from `knownPeople` — the live queue's own — rather than
 * from a second list written for the migration. "Is this a question" has to
 * have one answer across the product, or the script resolves a thread the
 * board would still be showing as a question.
 *
 * The roster spans EVERY thread passed in, not each doc separately. A person
 * who has only ever spoken on one task is still a person when an agent
 * addresses them on another, and a per-doc roster would call the same comment
 * a question on one board and a receipt on the next.
 */
export function triageThreads(input: { docId: string; threads: Thread[] }[]): MigrationPlan {
  const byDoc = new Map(input.map((d) => [d.docId, d.threads]));
  const people = knownPeople(byDoc.keys(), { threadsOf: (id) => byDoc.get(id) ?? [] });
  const triaged: ThreadTriage[] = [];
  for (const { docId, threads } of input) {
    for (const thread of threads) {
      const t = triageThread(docId, thread, people);
      if (t) triaged.push(t);
    }
  }
  return planMigration(triaged);
}

export function planMigration(triaged: ThreadTriage[]): MigrationPlan {
  const counts: Record<Disposition, number> = { question: 0, receipt: 0, skim: 0 };
  let declared = 0;
  for (const t of triaged) {
    counts[t.disposition] += 1;
    if (t.declared) declared += 1;
  }
  return { triaged, counts, declared };
}

/**
 * What this pass would resolve.
 *
 * Receipts only, and never one that already declares — resolving a live review
 * item would take it off the queue it was just put on. Both clauses are load
 * bearing and both are asserted.
 */
export function resolvable(plan: MigrationPlan): ThreadTriage[] {
  return plan.triaged.filter((t) => t.disposition === 'receipt' && !t.declared);
}

/**
 * The full disposition table, as text.
 *
 * Every row is printed, including the ones nothing will be done to — a table
 * that showed only the resolvable rows would be a report on the script rather
 * than on the queue, and the whole reason to run this in dry-run first is to
 * read the two classes it is NOT going to touch.
 */
export function formatPlan(plan: MigrationPlan, now: number): string {
  const lines: string[] = [];
  const order: Disposition[] = ['question', 'receipt', 'skim'];
  const heading: Record<Disposition, string> = {
    question: 'QUESTION — an agent reads these and files a Review Item. Not resolved here.',
    receipt: 'RECEIPT — opens with a closing verb. Resolved by --apply.',
    skim: 'SKIM — the heuristic cannot speak for these. Listed, never resolved.',
  };
  for (const d of order) {
    const rows = plan.triaged.filter((t) => t.disposition === d);
    lines.push('');
    lines.push(`${heading[d]}  (${rows.length})`);
    if (rows.length === 0) lines.push('  (none)');
    for (const r of rows) {
      const age = Math.max(0, Math.round(((now - r.since) / 86_400_000) * 10) / 10);
      const flags = [`${r.runLength} unanswered`, `${age}d`, r.lastBy];
      if (r.declared) flags.push('ALREADY DECLARED — skipped');
      lines.push(`  ${r.docId} ${r.threadId}  [${flags.join(' · ')}]`);
      lines.push(`      ${r.excerpt}`);
    }
  }
  lines.push('');
  lines.push(
    `TOTAL ${plan.triaged.length}  ·  question ${plan.counts.question}` +
      `  receipt ${plan.counts.receipt}  skim ${plan.counts.skim}` +
      `  ·  already declared ${plan.declared}` +
      `  ·  would resolve ${resolvable(plan).length}`,
  );
  return lines.join('\n');
}

// ── Reading the queue from a running server ─────────────────────────────
//
// Over HTTP rather than off disk. Two writers on one `.ydoc` is a hazard with
// a history in this repo, and the disk snapshot is debounced — a read straight
// off disk can be a second behind the doc a person is looking at.
//
// These live here, beside the classifier, rather than inside the CLI, because
// a CLI module runs its own `main` on import and so cannot be driven by a
// test. The end-to-end test drives THESE against the real routes, which is the
// only thing that proves the queue's field names and the reader's agree.

async function getJson(url: string): Promise<unknown> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → ${res.status} ${await res.text()}`);
  return res.json();
}

/**
 * The (docId, threadId) pairs currently in a workspace's review queue.
 *
 * The queue ITSELF, not a second enumeration of what might be in it — so the
 * script can never act on a thread the product would not have shown. It is
 * also what makes re-running safe: a resolved thread leaves the queue, so a
 * second pass finds nothing left to do rather than resolving it again.
 */
export async function fetchQueueRows(
  base: string,
  workspaceId: string,
): Promise<{ docId: string; threadId: string }[]> {
  const payload = (await getJson(
    `${base}/workspaces/${encodeURIComponent(workspaceId)}/review-items`,
  )) as { items?: { docId?: string; threadId?: string }[] };
  const seen = new Set<string>();
  const rows: { docId: string; threadId: string }[] = [];
  for (const item of payload.items ?? []) {
    const docId = item.docId;
    const threadId = item.threadId;
    if (docId === undefined || threadId === undefined) continue;
    // One thread can back more than one queue row. Triage is per THREAD, so a
    // duplicate would double-count it in the table and send two resolves.
    const key = `${docId}\0${threadId}`;
    if (seen.has(key)) continue;
    seen.add(key);
    rows.push({ docId, threadId });
  }
  return rows;
}

/**
 * Every thread on each doc the queue named — ALL of them, whatever the status.
 *
 * Two reasons it is the whole doc rather than the queued threads one by one.
 * The classifier needs every comment in the run and a queue row carries only a
 * clipped ask. And the roster is derived from what comes back, so it has to
 * include the threads a person spoke on and somebody has since resolved: the
 * live queue reads the roster from `allThreadsOf` for exactly this reason —
 * resolving one unrelated thread used to remove its author from the roster and
 * silently turn a live question back into a status note.
 *
 * Nothing extra gets triaged by widening this. `triageThread` answers null
 * whenever the unanswered run is empty, which is true of every resolved thread
 * and of every thread a person spoke on last — the queue's own membership rule.
 */
export async function fetchQueueThreads(
  base: string,
  workspaceId: string,
  rows: { docId: string; threadId: string }[],
): Promise<{ docId: string; threads: Thread[] }[]> {
  const docIds = [...new Set(rows.map((r) => r.docId))];
  const out: { docId: string; threads: Thread[] }[] = [];
  for (const docId of docIds) {
    const payload = (await getJson(
      `${base}/workspaces/${encodeURIComponent(workspaceId)}/docs/${encodeURIComponent(docId)}/threads`,
    )) as {
      threads?: Thread[];
    };
    out.push({ docId, threads: payload.threads ?? [] });
  }
  return out;
}

/**
 * Resolve the given rows, attributed to `author`.
 *
 * Soft by construction — `POST …/resolve` is the same verb the UI's resolve
 * button uses. Nothing is deleted, the thread keeps every comment, and a
 * person's reply reopens it.
 */
export async function resolveReceipts(
  base: string,
  workspaceId: string,
  author: string,
  rows: ThreadTriage[],
): Promise<{ resolved: ThreadTriage[]; failed: { row: ThreadTriage; error: string }[] }> {
  const resolved: ThreadTriage[] = [];
  const failed: { row: ThreadTriage; error: string }[] = [];
  for (const row of rows) {
    const url = `${base}/workspaces/${encodeURIComponent(workspaceId)}/docs/${encodeURIComponent(row.docId)}/threads/${encodeURIComponent(row.threadId)}/resolve`;
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ author: { name: author } }),
    });
    if (res.ok) resolved.push(row);
    else failed.push({ row, error: `${res.status} ${await res.text()}` });
  }
  return { resolved, failed };
}
