/**
 * The `instructions` string a client reads once, at initialize.
 *
 * Its own module because two hosts send it: the stdio child in `mcp.ts`, and
 * the shared server's `/mcp` endpoint. A copy in each would be two versions of
 * the one paragraph that tells an agent never to Write a bound file.
 */
export const CONNECTOR_INSTRUCTIONS = [
  'Every markdown attachment is backed by a .md file on disk. The file is the',
  'source of truth at rest; the live editor is the source of truth at runtime;',
  'the plugin keeps them in sync bidirectionally (~1s debounced).',
  '',
  'CREATE: call attach_markdown(docId, path) to bring a .md under review.',
  'The server reads the file, parses it into the live editor, sets up the',
  'fs.watch + write-back, and returns a reviewUrl you can hand to a human.',
  '',
  'EDIT: never use Write/Edit/str_replace on the .md while it is under review',
  '— direct filesystem edits race against the live doc’s own ~1s flush, and if',
  'the server has pending state your edit can be silently overwritten by the next',
  'write-back. Route edits through the MCP tools below: find_and_replace for',
  'prose changes, rewrite_thread_region / insert_after_thread / insert_blocks_after_thread',
  'for comment-anchored edits, and set_doc_content(docId, markdown) for a',
  'COMPREHENSIVE REWRITE of the whole doc (do NOT Write the file + reparse,',
  'and do NOT delete_doc + Write + re-create — both race the flush and both',
  'have destroyed content in the field). NEVER use set_doc_content on a doc a',
  'human is reviewing or editing: a scoped request (a comment, one section)',
  'gets a scoped edit — find_and_replace (table rows match in pipe syntax),',
  'rewrite_thread_region, edit_at_anchor — and a whole-doc rewrite built from',
  'an earlier read destroys their concurrent edits. The server refuses such a',
  'write with 409 stale-write naming the human-edit time; re-read with',
  'get_doc, re-apply your change onto the CURRENT content, and only retry',
  'with confirmOverwriteHumanEdits: true if a full rewrite is truly needed.',
  'External edits (VS Code, git pull)',
  'flow back into the live doc via the file poll when the server is idle; if you',
  'wrote to a bound file externally and need to be sure it landed, call',
  'reparse_from_disk(docId) to force-pull from disk. If an edit response or',
  'get_doc carries a `syncError`, read it — it names the conflict and where',
  'the overwritten version was backed up.',
  '',
  'DIFF REVIEW / FOLDER BROWSE: when the human wants to review your code',
  'changes ("review this diff", a branch, work in progress), call',
  'create_diff_review(repo, base) — one attachment per changed file,',
  'PR-style unified diff with line comments. Omit base to BROWSE a folder',
  'instead (no diff): everything is navigable from the all-files sidebar,',
  'files open lazily, markdown editable — works on plain folders and',
  'fresh repos too (attach_folder is an alias for this). Default mode diffs',
  'base against the LIVE working tree: keep editing the code and the reviewer',
  'sees your changes re-render within ~1s, with their comments riding along',
  '(threads orphan into the outdated-comments flow if their line disappears).',
  'ALWAYS pass groups: [{title, paths[]}] — organize the changed files by',
  'INTENT (the way you would split a branch into reviewable commits); you',
  'know the semantics of your change far better than the heuristic fallback.',
  'First group = read first; a directory path claims every file under it;',
  'unlisted files land in "Other". Pass target only to pin a review to a',
  'finished range. Re-run the tool after touching files that were not in',
  'the diff before (idempotent; refreshes the file list; keeps your groups',
  'unless you pass new ones). Share the returned entryUrl with the human',
  '(bare URL on its own line); the file tree navigates the rest. Thread',
  'events arrive per file via the auto-watch; resolve threads as you address',
  'them; refresh_attachment_set(setId) to re-sync membership and diffs as',
  'files move (threads survive); archive_attachment_set(setId, reason) when',
  'the review is done.',
  '',
  'SUGGEST: pass suggest: true on find_and_replace or rewrite_thread_region to',
  'PROPOSE a change instead of applying it — the match is marked pending and',
  'attributed to this agent; disk and every other reader stay on the accepted',
  'state until a human (or accept_suggestion) accepts it. Returns { suggestionId }.',
  'Use for judgment calls a reviewer should approve; use the plain edit for',
  'mechanical fixes. list_suggestions(docId) / accept_suggestion(docId, sid) /',
  'reject_suggestion(docId, sid) / resolve_all_suggestions(docId, action, authorId?)',
  'manage proposals from any author. suggestion.created/accepted/rejected events',
  'arrive on the same watch_doc channel as thread events.',
  '',
  'OBSERVE: call watch_doc(docId) once per doc to receive thread events as',
  '<channel source="claude-workspaces" doc_id="..." thread_id="..." event="..." author="..." sent_at="...">body</channel>',
  'messages. Treat each as an explicit ask from the reviewer; read, decide if it',
  "is in your domain, act via an edit tool. unwatch_doc when you're done.",
  'Watches are remembered on the server under this agent name (CW_AGENT_NAME)',
  'and re-wired when the session respawns; list_watched_docs says whether the',
  'current set was restored from the server or is session-only.',
  '',
  'CLEANUP: attachments are usually short-lived — bound for a ~30-minute',
  'feedback pass, then obsolete. When you no longer need one, call',
  'delete_doc(docId) to remove it (the bound source .md is left on disk; only',
  'the review session goes away). It refuses if the doc still has open threads',
  "(someone's waiting on that feedback) — resolve them first or pass force:true.",
  "Don't leave stale docs piling up in list_docs.",
  '',
  'BEFORE YOU EDIT A .md FILE: call list_docs first. If a doc has sourceUrl',
  'matching the path, route through the MCP. If not, normal file edits are fine.',
  '',
  'WORKSPACE BOARD: a board workspace is a goal + a task board + linked docs.',
  'create_workspace mints one; attach_doc links existing docs/attachments to it;',
  'create_tasks (ALWAYS a list — one idea is a one-item list) and',
  'spin_off_task add work (omit `goal` and the task lands UNPLACED in',
  'Backlog awaiting triage — the create says so and hands you the goal',
  'bands, and placing it with set_task_goal IS the triage:',
  'pick the goal AND the exact position). task_transition is the',
  'single gate for status changes — blockers come back in the result.',
  'attach_agent registers you as the workspace agent (heartbeat every few',
  'minutes to stay live; lead-addressed deliveries only reach live agents).',
  'Workspace events (task.*, decision.answered, workspace.goals_changed)',
  'arrive on the same channel as thread events once you create/attach.',
  'import_tasks_markdown moves an existing hand-maintained markdown tracker',
  'onto the board (dry-run first — review the mapping before apply:true).',
].join(' ');
